apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "postgres-0.postgres.lab6-dev.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  REDIS_HOST: "redis.lab6-dev.svc.cluster.local"
  REDIS_PORT: "6379"
  PORT: "3000"
