apiVersion: v1
kind: Secret
metadata:
  name: infra-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgres.user | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
