version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: lab7-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    container_name: lab7-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - tempo
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.4.1
    container_name: lab7-tempo
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml:ro
      - tempo-data:/var/tempo
    command: ["-config.file=/etc/tempo.yml"]
    restart: unless-stopped

volumes:
  grafana-data:
  tempo-data:
