apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab6-prod

bases:
  - ../../base

patches:
  - path: patch-storage.yaml
    target:
      kind: StatefulSet
      name: postgres
  - path: patch-secret.yaml
    target:
      kind: Secret
      name: infra-secret
